config/routes.rb
Rails.application.routes.draw do
  # get 'publishers/new'
  # get 'publishers/create'
  # get 'publishers/update'
  # get 'publishers/edit'
  # get 'publishers/distroy'
  # get 'publishers/index'
  # get 'publishers/show'
  # get 'authors/new'
  # get 'authors/create'
  # get 'authors/update'
  # get 'authors/edit'
  # get 'authors/distroy'
  # get 'authors/index'
  # get 'authors/show'
  # get 'categories/new'
  # get 'categories/create'
  # get 'categories/update'
  # get 'categories/edit'
  # get 'categories/distroy'
  # get 'categories/index'
  # get 'categories/show'
  get 'about/index'
  root 'books#index'
  resources :books
  resources :authors
  resources :categories
  resources :publishers
  get 'about' => 'about#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
	has_many :books
	validates :first_name,presence: true
	validates :last_name,presence: true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :category
	belongs_to :author
	belongs_to :publisher
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :books

	validates :name,presence: true,
				length: {minimum:3}
end

app/models/publisher.rb
class Publisher < ApplicationRecord
	has_many :books
	validates :name,presence: true,
				length: {minimum:3}
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  	@page_title = ' About Us'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def new
    @page_title = "add new Author"
    @author = Author.new
    @category = Author.new
    @author = Author.new
    @publisher = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      flash[:notice] = "new item created"
      redirect_to authors_path
    else
      flash[:alert] = "please insert any text to save"
      render 'new'
    end
  end

  def update
    @author = Author.find(params[:id])
    if @author.update(author_params)
       flash[:notice] = "item update"
      redirect_to authors_path
    else
      flash[:alert] = "please insert any text to save"
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    flash[:notice] = "item deleted"
    redirect_to authors_path
  end

  def index
    @authors = Author.all
  end

  def show
  end

  private
  def author_params
    params.require(:author).permit(:first_name,:last_name)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @page_title = "add new book"
    @book = Book.new
    @category = Category.new
    @author = Author.new
    @publisher = Publisher.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
       flash[:notice] = "new item created"
      redirect_to books_path
    else
      flash[:alert] = "please insert any text to save"
      render 'new'
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       flash[:notice] = "item update"
      redirect_to books_path
    else
      flash[:alert] = "please insert any text to save"
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "item deleted"
    redirect_to books_path
  end

  def index
    @books = Book.all
    @categories = Category.all
  end

  def show
    @book = Book.find(params[:id])
    @categories = Category.all
  end

  private
  def book_params
    params.require(:book).permit(:title, :category_id,:author_id,:publisher_id, :isbn, :buy, :price, :format, :excerpt, :pages, :year, :coverpath)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @page_title = "add new Category"
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "category created"
      redirect_to categories_path
    else
      flash[:alert] = "please insert any text to save"
      render 'new'
    end
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
       flash[:notice] = "item update"
      redirect_to categories_path
    else
      flash[:alert] = "please insert any text to save"
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = "item deleted"
    redirect_to categories_path
  end

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @books = @category.books
  end
  
  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def new
    page_title = "add new Publisher"
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(publisher_params)
    if @publisher.save
      flash[:notice] = "new item created"
      redirect_to publishers_path
    else
      flash[:alert] = "please insert any text to save"
      render 'new'
    end
  end

  def update
    @publisher = Publisher.find(params[:id])
    if @publisher.update(publisher_params)
       flash[:notice] = "item update"
      redirect_to publishers_path
    else
      flash[:alert] = "please insert any text to save"
    end
  end

  def edit
    @publisher = Publisher.find(params[:id])
  end

  def destroy
    @publisher = Publisher.find(params[:id])
    @publisher.destroy
    flash[:notice] = "item deleted"
    redirect_to publishers_path
  end

  def index
    @publishers = Publisher.all
  end

  def show
  end


  private
  def publisher_params
    params.require(:publisher).permit(:name)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/about/index.html.erb
<h1><%=@page_title%></h1>
<p>this is about us </p>

app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

app/views/authors/distroy.html.erb
<h1>Authors#distroy</h1>
<p>Find me in app/views/authors/distroy.html.erb</p>

app/views/authors/edit.html.erb
<h2>Edit author</h2>
<%= form_for @author do |f| %>
	<div class = "from-group">
		<%= f.label :first_name %><br/>
		<%= f.text_field :first_name ,class: 'form-control'%><br/>
	</div>
	<div class = "from-group">
		<%= f.label :last_name %><br/>
		<%= f.text_field :last_name ,class: 'form-control'%><br/>
	</div>
	<%= f.submit "submit", class:'btn btn-primary' %>
	<%= link_to "cancel", authors_path, class:'btn btn-default' %>

<% end %>

app/views/authors/index.html.erb
<h2>Authors</h2>
<table class= "table table-striped">
    <tr>
        <th>Author</th>
        <th>action</th>
    </tr>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.first_name + " " + author.last_name %></td>
        <td><%= link_to 'Edit', edit_author_path(author.id)%> | <%= link_to 'Delete',
         author_path(author),method: :delete,data:{confirm:'Are you sure?'} %></td>        
      </tr>
    <% end %>
</table>

app/views/authors/new.html.erb
<h2>add new author</h2>
<%= form_for @author do |f| %>
	<div class = "from-group">
		<%= f.label :first_name %><br/>
		<%= f.text_field :first_name ,class: 'form-control'%><br/>
	</div>
	<div class = "from-group">
		<%= f.label :last_name %><br/>
		<%= f.text_field :last_name ,class: 'form-control'%><br/>
	</div>
	<%= f.submit "submit", class:'btn btn-primary' %>
	<%= link_to "cancel", authors_path, class:'btn btn-default' %>

<% end %>

app/views/authors/show.html.erb
<h1>Authors#show</h1>
<p>Find me in app/views/authors/show.html.erb</p>

app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/distroy.html.erb
<h1>Books#distroy</h1>
<p>Find me in app/views/books/distroy.html.erb</p>

app/views/books/edit.html.erb
<h2>edit book</h2>
<%= form_for @book do |f| %>
	<div class = "from-group">
		<%= f.label :title %><br/>
		<%= f.text_field :title ,class: 'form-control'%><br/>
	</div>
	<div class = "from-group">
		<%= f.label :isbn %><br/>
		<%= f.text_field :isbn ,class: 'form-control'%><br/>
	</div>
	<div class = "from-group">
		<%= f.label :category %><br/>
		<%= f.select :category_id,Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'select one'} ,class: 'form-control'%><br/>
	</div>
	<div class = "from-group">
		<%= f.label :author %><br/>
		<%= f.select :author_id,Author.all.collect {|x| [x.first_name+' '+x.last_name, x.id]}, {:include_blank => 'select one'} ,class: 'form-control'%><br/>
	</div>
	<div class = "from-group">
		<%= f.label :publisher %><br/>
		<%= f.select :publisher_id,Publisher.all.collect {|x| [x.name, x.id]}, {:include_blank => 'select one'} ,class: 'form-control'%><br/>
	</div>
	<div class = "from-group">
		<%= f.label :format %><br/>
		<%= f.text_field :format,class: 'form-control'%><br/>
	</div>
	<div class = "from-group">
		<%= f.label :excerpt %><br/>
		<%= f.text_area :excerpt,class: 'form-control'%><br/>
	</div>
	<div class = "from-group">
		<%= f.label :pages %><br/>
		<%= f.number_field :pages,class: 'form-control'%><br/>
	</div>
	<div class = "from-group">
		<%= f.label :price %><br/>
		<%= f.text_field :price,class: 'form-control'%><br/>
	</div>
	<div class = "from-group">
		<%= f.label :buy %><br/>
		<%= f.text_field :buy,class: 'form-control'%><br/>
	</div>
	<div class = "from-group">
		<%= f.label :year %><br/>
		<%= f.text_field :year,class: 'form-control'%><br/>
	</div>
	<div class = "from-group">
		<%= f.label :coverpath %><br/>
		<%= f.text_field :coverpath,class: 'form-control'%><br/>
	</div>
	<%= f.submit "submit", class:'btn btn-primary' %>
	<%= link_to "cancel", categories_path, class:'btn btn-default' %>

<% end %>

app/views/books/index.html.erb
<div id="books-index">
	<% @books.each_slice(4) do |book| %>
		<div class="row">
			<%book.each do |book| %>
				<div class="col-md-3 col-sm-3">
					<h3> <%= book.title %> </h3>
					<%= image_tag(book.coverpath)%>
					<%= link_to 'read more' , book_path(book) , class: 'btn btn-primary' %>
				</div>
			<% end %>
		</div>
	<% end %>
</div>

ltms.medu.ir
96073538

app/views/books/new.html.erb
<h2>add new book</h2>
<%= form_for @book do |f| %>
	<div class = "from-group">
		<%= f.label :title %><br/>
		<%= f.text_field :title ,class: 'form-control'%><br/>
	</div>
	<div class = "from-group">
		<%= f.label :isbn %><br/>
		<%= f.text_field :isbn ,class: 'form-control'%><br/>
	</div>
	<div class = "from-group">
		<%= f.label :category %><br/>
		<%= f.select :category_id,Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'select one'} ,class: 'form-control'%><br/>
	</div>
	<div class = "from-group">
		<%= f.label :author %><br/>
		<%= f.select :author_id,Author.all.collect {|x| [x.first_name+' '+x.last_name, x.id]}, {:include_blank => 'select one'} ,class: 'form-control'%><br/>
	</div>
	<div class = "from-group">
		<%= f.label :publisher %><br/>
		<%= f.select :publisher_id,Publisher.all.collect {|x| [x.name, x.id]}, {:include_blank => 'select one'} ,class: 'form-control'%><br/>
	</div>
	<div class = "from-group">
		<%= f.label :format %><br/>
		<%= f.text_field :format,class: 'form-control'%><br/>
	</div>
	<div class = "from-group">
		<%= f.label :excerpt %><br/>
		<%= f.text_area :excerpt,class: 'form-control'%><br/>
	</div>
	<div class = "from-group">
		<%= f.label :pages %><br/>
		<%= f.number_field :pages,class: 'form-control'%><br/>
	</div>
	<div class = "from-group">
		<%= f.label :price %><br/>
		<%= f.text_field :price,class: 'form-control'%><br/>
	</div>
	<div class = "from-group">
		<%= f.label :buy %><br/>
		<%= f.text_field :buy,class: 'form-control'%><br/>
	</div>
	<div class = "from-group">
		<%= f.label :year %><br/>
		<%= f.text_field :year,class: 'form-control'%><br/>
	</div>
	<div class = "from-group">
		<%= f.label :coverpath %><br/>
		<%= f.text_field :coverpath,class: 'form-control'%><br/>
	</div>
	<%= f.submit "submit", class:'btn btn-primary' %>
	<%= link_to "cancel", categories_path, class:'btn btn-default' %>

<% end %>

app/views/books/show.html.erb
<div id ="books-show">
	<h2><%= @book.title %></h2>
	<div class="books-show-left">
		<%= image_tag(@book.coverpath)%>
	</div>
	<div class="books-show-right">
		<h3>books info:</h3>
		<ul>
			<li><strong>category: </strong> <%= @book.category.name %> </li>
			<li><strong>author: </strong><%= @book.author.first_name+" "+@book.author.last_name %></li>
			<li><strong>publisher: </strong><%= @book.publisher.name %></li>
			<li><strong>year: </strong><%= @book.year %></li>
			<li><strong>isbn: </strong><%= @book.isbn %></li>
			<li><strong>format: </strong><%= @book.format %></li>
			<li><strong>pages: </strong><%= @book.pages %></li>
			<%= link_to 'buy for $'+@book.price , @book.buy , class: 'btn btn-success',target:'_blank' %>
		</ul>
	</div>
	<div class="clearfix"></div>
	<h4>excerpt: </h4>
	<p><%= @book.excerpt %></p>
	<h3>Admin function</h3>
	<%= link_to 'Edit',edit_book_path(@book.id) %> | <%= link_to 'Delete',book_path(@book),method: :delete, data: {confirm:'Are you sure?'} %> 
</div>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/distroy.html.erb
<h1>Categories#distroy</h1>
<p>Find me in app/views/categories/distroy.html.erb</p>

app/views/categories/edit.html.erb
<h2>edit category</h2>
<%= form_for @category do |f| %>
	<div class = "from-group">
		<%= f.label :name %><br/>
		<%= f.text_field :name ,class: 'form-control'%><br/>
	</div>
	
	<%= f.submit "submit", class:'btn btn-primary' %>
	<%= link_to "cancel", categories_path, class:'btn btn-default' %>

<% end %>

app/views/categories/index.html.erb
<h2>Categories</h2>
<table class= "table table-striped">
    <tr>
        <th>category</th>
        <th>action</th>
    </tr>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name%></td>
        <td><%= link_to 'Edit', edit_category_path(category.id)%> | <%= link_to 'Delete',
         category_path(category),method: :delete,data:{confirm:'Are you sure?'} %></td>        
      </tr>
    <% end %>
</table>

app/views/categories/new.html.erb
<h2>add new category</h2>
<%= form_for @category do |f| %>
	<div class = "from-group">
		<%= f.label :name %><br/>
		<%= f.text_field :name ,class: 'form-control'%><br/>
	</div>
	
	<%= f.submit "submit", class:'btn btn-primary' %>
	<%= link_to "cancel", categories_path, class:'btn btn-default' %>

<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<div id="books-index">
	<% @books.each_slice(4) do |book| %>
		<div class="row">
			<%book.each do |book| %>
				<div class="col-md-3 col-sm-3">
					<h3> <%= book.title %> </h3>
					<%= image_tag(book.coverpath)%>
					<%= link_to 'read more' , book_path(book) , class: 'btn btn-primary' %>
				</div>
			<% end %>
		</div>
	<% end %>
</div>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title ? @page_title : 'welcome' %> | Bookstore</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>

  <body>
    <div class="navbar navbar-expand-md navbar-dark bg-dark fixed-top"> 
      <nav>   
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
          <ul class="navbar-nav mr-auto">
            <li class="<%= params[:container] == 'books' ? 'active' : '' %>"><%=link_to 'Home' , root_path ,class: "nav-link" %></li>
            <li><%=link_to 'About' , about_path ,class: "nav-link" %></li>
          </ul>
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Add New
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <%= link_to 'Book' , new_book_path ,class: "dropdown-item" %>
              <%= link_to 'Authors' , new_author_path ,class: "dropdown-item" %>
              <%= link_to 'Categories' , new_category_path ,class: "dropdown-item" %>
              <%= link_to 'Publishers' , new_publisher_path ,class: "dropdown-item" %>
            </div>
          </div>

          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Manage
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <%=link_to 'Authors' , authors_path ,class: "dropdown-item" %>
              <%=link_to 'Categories' , categories_path ,class: "dropdown-item" %>
              <%=link_to 'Publishers' , publishers_path ,class: "dropdown-item" %>
            </div>
          </div>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
    </div>
    <header>
      <div class="container">
        <h1>The bookstore<small><%= @page_title ? @page_title : ' welcome' %></small></h1>
      </div>
    </header>
    <section>
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <% if flash[:notice]%>
              <div class="alert alert-success"><%= flash[:notice] %></div>
            <% end %>
            <% if flash[:alert]%>
              <div class="alert alert-danger"><%= flash[:alert] %></div>
            <% end %>

            <%= yield %>
          </div>
          <div class="col-md-4">
            <%= render  "partials/sidebar" %>
          </div>
        </div>
      </div>
    </section>
    <footer>
      <div calss= "container">
        <p>CopyRight &copy; 2018, salarhp</p>
      </div>
    </footer>
  </body>
</html>

app/views/partials/_sidebar.html.erb
<% if params[:controller] == "about" %>
	<div calss= "well">
		<ul>
			<h3>location us</h3>
			<li>contry:iran </li>
			<li>address: kurdestan, sanandaj</li>
			<li>phone: 0981234567</li>
			<li>email: asdasdas@adsd.dfdf</li>
		</ul>
	</div>
<% end %>

<% if params[:controller] == "books" && params[:action] == "index" || params[:action] == "show" %>
	<div class="list-group">
		<% @categories.each do |category| %>
	  		<%= link_to category.name, category_path(category.id) , class: 'list-group-item'%>
  		<% end %>
	</div>
<% end %>

app/views/publishers/create.html.erb
<h1>Publishers#create</h1>
<p>Find me in app/views/publishers/create.html.erb</p>

app/views/publishers/distroy.html.erb
<h1>Publishers#distroy</h1>
<p>Find me in app/views/publishers/distroy.html.erb</p>

app/views/publishers/edit.html.erb
<h2>Edit publisher</h2>
<%= form_for @publisher do |f| %>
	<div class = "from-group">
		<%= f.label :name %><br/>
		<%= f.text_field :name ,class: 'form-control'%><br/>
	</div>
	<%= f.submit "submit", class:'btn btn-primary' %>
	<%= link_to "cancel", publishers_path, class:'btn btn-default' %>

<% end %>

app/views/publishers/index.html.erb
<h2>publisher</h2>
<table class= "table table-striped">
    <tr>
        <th>publisher</th>
        <th>action</th>
    </tr>
    <% @publishers.each do |publisher| %>
      <tr>
        <td><%= publisher.name %></td>
        <td><%= link_to 'Edit', edit_publisher_path(publisher.id)%> | <%= link_to 'Delete',
         author_path(publisher),method: :delete,data:{confirm:'Are you sure?'} %></td>        
      </tr>
    <% end %>
</table>

app/views/publishers/new.html.erb
<h2>add new publisher</h2>
<%= form_for @publisher do |f| %>
	<div class = "from-group">
		<%= f.label :name %><br/>
		<%= f.text_field :name ,class: 'form-control'%><br/>
	</div>
	<%= f.submit "submit", class:'btn btn-primary' %>
	<%= link_to "cancel", publishers_path, class:'btn btn-default' %>

<% end %>

app/views/publishers/show.html.erb
<h1>Publishers#show</h1>
<p>Find me in app/views/publishers/show.html.erb</p>

app/views/publishers/update.html.erb
<h1>Publishers#update</h1>
<p>Find me in app/views/publishers/update.html.erb</p>